### ISSUE TITLE
Web Toaster

### ISSUE THREAD

**Issue by simonaronsson** [arcticbit/Hale.Monitoring#19]
Build a web toaster for receiving and handling notifications and alerts inside of Hale UI

**Comment by piksel** [comment]
![](http://worth1000.s3.amazonaws.com/submissions/757500/757822_dbc0_1024x2000.jpg)

**Comment by simonaronsson** [comment]
More like:

![image](https://cloud.githubusercontent.com/assets/1596025/18008583/fe487d9e-6ba8-11e6-947f-0dd3b8b2a204.png)

But your suggestion is way better.

**Comment by simonaronsson** [comment]
A toaster have been implemented. As of right now, it only handles static toasts, and one at a time.
However, we should consider adding more flexibility when needed instead of over-engineering from the beginning.

The current solution builds on using states to push to a error-state, which should change the ui-view "toast" to the notification that you'd like to display. See /views/toasts/login-failed.html for examples together with the app.login.failed route.

Further discussion, suggestions or what not should be taken in a new ticket linked to this one.
